# Generated by Django 4.1.2 on 2022-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('python_skill', models.IntegerField(default=0)),
                ('sql_skill', models.IntegerField(default=0)),
                ('java_skill', models.IntegerField(default=0)),
                ('spark_skill', models.IntegerField(default=0)),
                ('html_css_skill', models.IntegerField(default=0)),
            ],
        ),
    ]
